spring:
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false

liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

---
spring:
    profiles: dev

    datasource:
        url: jdbc:h2:mem:follow
        driverClassName: org.h2.Driver
        username: sa
        password: sa

liquibase:
    change-log: classpath:/liquibase/changelog-test-data.xml

